<?php

use rock\i18n\i18n;

/**
 * Translates a string to the current language or to a given language.
 */
function t($string, $args = array()) {
  global $default_language;

  $i18n = new i18n;
  $paths = [
    'en' => [
         'sites/langs/en/lang.php',
     ]
  ];
  $i18n->addDicts($paths);

  try {
    return $i18n->translate($string, $args);
  } catch (\Exception $e) {
    return $string;
  }
}
